# Makefile.common
# Michal Ludvig <michal@logix.cz>

CC	= gcc
CXX	= g++
MAKE	= make
CPP	= $(CC) -E
AR	= ar
STRIP	= strip

CFLAGS  = -I$(TOPDIR)/util -Wall -g -O2
ARCHDIR = $(TOPDIR)/arch

.c.s:
	$(CC) $(CFLAGS) -S -o $*.s $<
.s.o:
	$(AS) -c -o $*.o $<
.c.o:
	$(CC) $(CFLAGS) -c -o $*.o $<
.cc.o:
	$(CXX) $(CFLAGS) -c -o $*.o $<
